---
pages:
- post/2017-12-09.md
- post/dewitt-clause.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- type: boolean
  name: draft
  label: draft
  hidden: false
  default: true
