---
pages:
- post/2018-01-18.md
- post/2018-01-17.md
- post/2018-01-16.md
- post/2018-01-15.md
- post/2018-01-14.md
- post/2018-01-04.md
- post/2018-01-05.md
- post/2018-01-06.md
- post/2018-01-07.md
- post/2018-01-08.md
- post/2018-01-09.md
- post/2018-01-10.md
- post/2018-01-11.md
- post/2018-01-12.md
- post/2018-01-13.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- type: boolean
  name: draft
  label: draft
  hidden: false
  default: true
