---
pages:
- the-plan.md
- post/2018-01-09.md
- post/2018-01-08.md
- post/2018-01-07.md
- post/2018-01-06.md
- post/2018-01-05.md
- post/2018-01-04.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- type: boolean
  name: draft
  label: draft
  hidden: false
  default: true
